"""add_model_id_to_model_versions

Revision ID: 93fc0ab4c15b
Revises: 143870a5013f
Create Date: 2025-08-07 12:52:11.281661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fc0ab4c15b'
down_revision: Union[str, Sequence[str], None] = '143870a5013f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('model_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'model_id')
    # ### end Alembic commands ###
