"""Add model metrics tables

Revision ID: c3dc00860506
Revises: 4bec3792c2fb
Create Date: 2025-07-09 11:38:09.577146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3dc00860506'
down_revision: Union[str, Sequence[str], None] = '4bec3792c2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('random_forest_value', sa.Float(), nullable=False),
    sa.Column('xgboost_value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comparison_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_feature_importances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('importance_value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease_clustering_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clustering_method', sa.String(), nullable=False),
    sa.Column('cluster_label', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('diseases', sa.JSON(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('treatments', sa.JSON(), nullable=True),
    sa.Column('outcomes', sa.JSON(), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Integer(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease_clustering_results')
    op.drop_table('model_metrics')
    op.drop_table('model_feature_importances')
    op.drop_table('model_comparisons')
    # ### end Alembic commands ###
